### ISSUE TITLE
Duplicate Entry : com/facebook/internal/BundleJSONConverter$Setter.class

### ISSUE THREAD

**Issue by roua914** [taessina/react-native-paypal-wrapper#3]
Hello ,
I have this error when i try to install react-native-wrapper-paypal :
Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/facebook/internal/BundleJSONConverter$Setter.class

Please does anyone have an idea about how to fix it.

**Comment by dmi3coder** [comment]
This bug caused by BundleJSONConverter contained in this project: 
https://github.com/taessina/react-native-paypal-wrapper/blob/master/android/src/main/java/com/facebook/internal/BundleJSONConverter.java
As I think, you have some dependency such as **react-native-fbsdk** that also contains this file. 

This is bad practice to create classes not from your package, so perfectly this class must be removed from this library.

**Comment by alvinthen** [comment]
Fixed in v1.1.0, thanks to @dashracer
