### ISSUE TITLE
undefined is not an object (evaluating '_reactNativePaypalWrapper2.default.initializer')

### ISSUE THREAD

**Issue by NirmalsinhRathod** [taessina/react-native-paypal-wrapper#7]
Hey I am using your paypal wrapper. I already did all the steps which is necessary to config in xcode and react native both. When I try to run code for paypal, it throw me an error.  Any solution?

![simulator screen shot - iphone 6 - 2018-01-18 at 16 45 04](https://user-images.githubusercontent.com/11387256/35095909-43288644-fc70-11e7-8fc0-6e5f3395e2a4.png)

**Comment by fpena** [comment]
I was having the same problem yesterday, but I managed to fix it. 

1. Add the library with yarn: `yarn add react-native-paypal-wrapper`
2. Link the library: `react-native link react-native-paypal-wrapper`
3. Instead of adding the libraries and changes from this [link](https://github.com/paypal/PayPal-ios-SDK#with-or-without-cocoapods), JUST ADD the URL schemes to the Xcode project / plist file. 

That should solve it.

**Comment by geniuscd** [comment]
@fpena thank you for your reply, actually I'm also having problem integrating payapl into react native.
how did you managed to bypass this error? I tried your workaround, but didn't worked. any feedback?

**Comment by fpena** [comment]
@geniuscd I remember the issue was related to linking the library (with `react-native link` command). You should avoid that step and just add the url to the schemes.

**Comment by alvinthen** [comment]
Is this issue still valid? If possible, please provide a reproducible repo. I'll be glad to help, but we have limited resources :)

**Comment by geniuscd** [comment]
The way I fixed it that I created a new empty React native app, and moved all my `src/` files to the new app and checked the dependencies one by one until all are installed and are working properly. didn't use `yarn`
